[package]
name = "mithra"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
assert_matches = "1.5.0"
anyhow = "1.0"
rustyline = "13.0.0"